[package]
name = "ubs"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = "0.26.0"
tl = "0.7.7"
hyper = { version = "0.14.23", features = ["client", "http1"] }
hyper-rustls = "0.23.1"
cookie = "0.16.1"
futures = "0.3.25"
chrono = "0.4.23"
thiserror = "1.0.37"

[features]
# Enables SIMD accelerated parsing for HTML (requires nightly)
simd = ["tl/simd"]
