[package]
name = "ubs"
version = "0.1.0"
edition = "2021"

authors.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
thiserror = "1.0.40"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.95"
ubs-lib = { path = "../ubs-lib" }
chrono = { version = "0.4.24", features = ["serde"] }
futures = "0.3.28"
tokio = { version = "1.26.0", features = [
    "rt",
    "macros",
], default-features = false }
miette = { version = "5.7.0", features = ["fancy"] }
