name: check
on:
  workflow_dispatch:
  push:
    paths:
      - "**.rs"
  pull_request:
    paths:
      - "**.rs"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: switch to nightly toolchain
        run: rustup default nightly

      - name: clippy
        run: cargo clippy --all-features
        env:
          RUSTFLAGS: "-Dwarnings"
  
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: switch to nightly toolchain
        run: rustup default nightly

      - name: rustfmt
        run: cargo fmt --all -- --check