name: check
on:
  workflow_dispatch:
  push:
    paths:
      - "**.rs"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "**.rs"
      - ".github/workflows/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: switch to nightly toolchain
        run: |
          rustup default nightly
          rustup component add clippy

      - name: clippy
        run: cargo clippy --all-features
        env:
          RUSTFLAGS: "-Dwarnings"
  
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: switch to nightly toolchain
        run: |
          rustup default nightly
          rustup component add rustfmt

      - name: rustfmt
        run: cargo fmt --all -- --check