name: test
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # nightly

jobs:
  postman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: run tests
        run: cargo test --all-features